### ISSUE TITLE
please update to 1.x

### ISSUE THREAD

**Issue by lorvent** [amimaro/generator-vuepress#2]
Hello,
please update to 1.x

 i tried installing vuepress@next globally

but i can confirm, it may not be working.

latest version has `last updated` plugin included by default but its not showing up
i even tried adding plugin manually still not luck.

**Comment by amimaro** [comment]
Hi,
I just updated some dependencies. Can you send the terminal output?

**Comment by lorvent** [comment]
May be its not related to repo but instructions,

in read me,  where it says to install vuepress globally, may be you should mention vuepress@next

 because i did that locally and i can confirm it is using 1.x now.

**Comment by lorvent** [comment]
BTW, is there any way we can improve pdf generation?

like gitbook generates?

thanks.

**Comment by amimaro** [comment]
Did it worked for you usign vuepress@next?

Maybe you can try installing vuepress with yarn, like this `yarn global add vuepress`
It worked better for me, instead of installing with npm.
I just looked at vuepress [docs](https://vuepress.vuejs.org/). At the main page they use '@next' at the end but at the [Getting Started](https://vuepress.vuejs.org/guide/getting-started.html) section of the guide it's without '@next'

**Comment by lorvent** [comment]
yes, it works when i use `vuepress@next` both globally and locally.

yeah...docs may be confusing a bit but it shows a notification mentioning those docs are for 1.x
